### ISSUE TITLE
Cheatsheets

### ISSUE THREAD

**Issue by erwanosouf** [blank-project/_blank#14]
- [x] Raccourcis clavier
- [x] Terminal
- [x] Git

**Comment by erwanosouf** [comment]
En cours, commit : https://github.com/blank-project/_blank/commit/cdaf35aad8392366c7f6b632ec5f05ee45737140
Les premiers drafts sont dans le dossier cheatsheets.

**Comment by FaXaq** [comment]
https://github.com/blank-project/_blank/projects/1#card-153457
