### ISSUE TITLE
Mettre à Jour la charte graphique du site du cours

### ISSUE THREAD

**Issue by erwanosouf** [blank-project/_blank#23]
Histoire qu'elle soit en accord avec le site _blank.

**Comment by erwanosouf** [comment]
Du coup, il faudrait pouvoir extraire certaines partie du skin du site _blank

**Comment by FaXaq** [comment]
Hmmm on est bon pour les cours mais pas pour les index, peut-être incorporer un style de base pour les index ?

**Comment by erwanosouf** [comment]
Yep, mais ça urge pas

**Comment by FaXaq** [comment]
déjà commencé, check sur le site blank avec le style 6e855b280f48903a8a6d22a0f149a106278fe17d
