### ISSUE TITLE
Ecrire le cours sur la structure d'une page web

### ISSUE THREAD

**Issue by erwanosouf** [blank-project/_blank#27]

**Comment by erwanosouf** [comment]
- Header, Footer, Nav, Section, article
- Tableaux
- Retour sur les listes et sous-listes
- Balises exotiques (blockquotes ...)

**Comment by erwanosouf** [comment]
Closed as already done by  @FaXaq

**Comment by FaXaq** [comment]
It's still missing tables, & exotic html tags

Marin Procureur

2016-11-11 21:43 GMT+01:00 Erwan Osouf notifications@github.com:

**Comment by erwanosouf** [comment]
Other tags should go in another course (or do we simply give them the Cheatsheet and Exercises ?)
